 
# project_root/.travis.yml
matrix:
  include:
  - language: node_js 
    node_js:
    - '10'
    before_install:
    - cd ./front-end/wearhouse
    install:
    - yarn install
    script:
    - yarn test --coverage --watchAll=false
    
    
    
