 
# project_root/.travis.yml
matrix:
  include:
  - language: node_js # Your language e.g. node_js, python
    node_js:
    - '10'
    before_install:
    - cd ./front-end/wearhouse
    install:
    - yarn install
    script:
    - ./node_modules/.bin/eslint src
    - yarn test --coverage --watchAll=false
    
    
    
