 
# project_root/.travis.yml
matrix:
  include:
  - language: node_js 
    node_js:
    - '10'
    before_install:
    - cd ./front-end/wearhouse
    install:
    - yarn install
    script:
    - yarn test --coverage --watchAll=false
  - language: python
    python:
    - '3.7'
    before_install:
    - cd ./back-end/wearhouse
    install: 
    - pip install -r requirements.txt
    script:
    - coverage run --branch --source='.' manage.py test
    - coverage report --fail-under=80 -m
    
    
    
